### ISSUE TITLE
How to Build Shards Tutorial

### ISSUE THREAD

**Issue by ChelseaChX** [fragcolor-xyz/shards-examples#21]
- [x] Write 1st draft of how to build shards tutorial
- [x] Let Shar try to build it following tutorial
- [x] Work on comments/edits

**Comment by ChelseaChX** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards-examples/21?planning-poker) with Zenhub @ChelseaChX @ShahFragcolor @sinkingsugar

**Comment by Kryptos-FR** [comment]
Can this be closed?

**Comment by ChelseaChX** [comment]
> Can this be closed?

There's still some outstanding issues such as catering for different operating systems, but I think the issue by itself should be completed.

**Comment by Kryptos-FR** [comment]
Yes, we can tackle additional issues later. Closing.
