### ISSUE TITLE
Review How to Document using mkdocs

### ISSUE THREAD

**Issue by ChelseaChX** [fragcolor-xyz/shards-examples#23]
- [x] Review how mkdocs is used to document current documentation
- [x] Follow tutorials / Research mkdocs
- [x] Do a sample tutorial

**Comment by ChelseaChX** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Whole-Team-623c70cfcdeee40011bd03e3/issues/fragcolor-xyz/shards-examples/23?planning-poker) with Zenhub @ChelseaChX @ShahFragcolor @sinkingsugar

**Comment by Kryptos-FR** [comment]
I can help with that if you have any questions since I wrote the CI script that builds the doc and the website.

**Comment by ChelseaChX** [comment]
> I can help with that if you have any questions since I wrote the CI script that builds the doc and the website.

Noted with thanks!

**Comment by ChelseaChX** [comment]
[Sample tutorial is done](https://docs.google.com/document/d/1mxdTOlMDLGpIaSaemZeub7W_An2GnTYw9kgPJ-7Zu5A/edit?usp=sharing), but still needs polishing and converting to markdown.
