### ISSUE TITLE
Displaying of enum values on each shard's API page

### ISSUE THREAD

**Issue by ChelseaChX** [fragcolor-xyz/shards-examples#45]
- [ ] Shards that use enums for their parameters should have the enums documented down on their API page

**Comment by ChelseaChX** [comment]
Related to: https://github.com/fragcolor-xyz/shards/issues/329

**Comment by Kryptos-FR** [comment]
Is that fixed by having a link to the enum page (fragcolor-xyz/shards#478, fragcolor-xyz/shards#516)? Or do you want to track the enums that are still missing description in this issue?

**Comment by ChelseaChX** [comment]
> Is that fixed by having a link to the enum page ([fragcolor-xyz/shards#478](https://github.com/fragcolor-xyz/shards/issues/478), [fragcolor-xyz/shards#516](https://github.com/fragcolor-xyz/shards/pull/516))? Or do you want to track the enums that are still missing description in this issue?

I think we can close it for now! The missing enums will be tracked in a separate issue. Thank you for the help with this.
