### ISSUE TITLE
Outdated shard "Dispatch" used in yes-no game tutorial

### ISSUE THREAD

**Issue by Yttruire** [fragcolor-xyz/shards-examples#54]
The "Dispatch" shard, likely an alias for what is now known as "Step" is used in the full code for Yes-No tutorial game. The correct shard "Step" is used in prior parts

<img width="353" alt="image" src="https://user-images.githubusercontent.com/34051887/237012636-613fae2b-9a3e-461f-b8ec-611adb357785.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/34051887/237012684-4e4a80ff-b0a8-42c6-93f7-e53e956a27b4.png">

**Comment by sinkingsugar** [comment]
Actually should be `Do` I think, `Step` is a bit more complex (as it steps its own coroutine).
`Dispatch` was removed and it's like `Do` basically.

**Comment by Yttruire** [comment]
According to Part 4 https://docs.fragnova.com/learn/shards/tutorials/yes-no-game/steps/step-4/#ending-a-round

Seems like `end-round` is intended to be constructed as a looped wire, and as a result `Step` is preferred over `Do` in this particular case, in order to retain the context in the looped wire across repetitive calls to `end-round`
https://docs.fragnova.com/learn/shards/tutorials/yes-no-game/steps/step-5/#checking-the-input

So I think there might be some refactoring required if we change it to `Do` instead.
